// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOE_8rqbCRALBgsQFzHfjyZpUFNA1qF3A',
    appId: '1:924214570624:web:6f34b00c3b89a74ff6c065',
    messagingSenderId: '924214570624',
    projectId: 'hobbyhub-dev',
    authDomain: 'hobbyhub-dev.firebaseapp.com',
    storageBucket: 'hobbyhub-dev.firebasestorage.app',
    measurementId: 'G-GZ1CGJNEJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL_MUbgacEvig9TQh8v5NxIccnV1F_5YU',
    appId: '1:924214570624:android:8bc3efe8c3476650f6c065',
    messagingSenderId: '924214570624',
    projectId: 'hobbyhub-dev',
    storageBucket: 'hobbyhub-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-9AZbuJhfY6QEJ2dhXdrApBL9_V4b7O4',
    appId: '1:924214570624:ios:9dd53d48b0e54416f6c065',
    messagingSenderId: '924214570624',
    projectId: 'hobbyhub-dev',
    storageBucket: 'hobbyhub-dev.firebasestorage.app',
    iosBundleId: 'com.example.hobbyHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-9AZbuJhfY6QEJ2dhXdrApBL9_V4b7O4',
    appId: '1:924214570624:ios:9dd53d48b0e54416f6c065',
    messagingSenderId: '924214570624',
    projectId: 'hobbyhub-dev',
    storageBucket: 'hobbyhub-dev.firebasestorage.app',
    iosBundleId: 'com.example.hobbyHub',
  );
}