services:
  # Планируемые сервисы:
  #  backend:
  #    build: ./backend
  #    restart: always
  #
  #  postgres:
  #    image: postgres:16
  #    environment:
  #      - POSTGRES_DB=hobbyhub
  #      - POSTGRES_PASSWORD=password
